#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'duckdb/**'
      - 'extension-ci-tools/**'
      - 'CMakeLists.txt'
      - 'extension_config.cmake'
      - 'vcpkg.json'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - 'duckdb/**'
      - 'extension-ci-tools/**'
      - 'CMakeLists.txt'
      - 'extension_config.cmake'
      - 'vcpkg.json'
      - '.github/workflows/**'
  workflow_dispatch:



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  # This is useful for debugging issues regarding the secret management:
  #
  # test-secrets-accessable:
  #   name: Test secrets accessable
  #   uses: ./.github/workflows/_check_secrets.yml
  #   secrets: inherit



  duckdb-stable-build-v1-4-2:
    name: Build extension binaries (DuckDB v1.4.2)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5.0
    with:
      duckdb_version: v1.4.2
      ci_tools_version: v1.5.0
      extension_name: sheetreader
      exclude_archs: "windows_amd64_rtools"

  duckdb-stable-build-v1-5-0:
    name: Build extension binaries (DuckDB v1.5.0)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5.0
    with:
      duckdb_version: v1.5.0
      ci_tools_version: v1.5.0
      extension_name: sheetreader
      exclude_archs: "windows_amd64_rtools"

